name: PR Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  JAVA_VERSION: ${{ vars.JAVA_VERSION || '17' }}
  JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
  MAVEN_OPTS: ${{ vars.MAVEN_OPTS }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_DISTRIBUTION }}/${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn -B clean install

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc
